name: couldai_user_app
description: "ShinCare Pro - Your Daily Wellness Partner"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^1.4.0
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  path_provider: ^2.0.0
  flutter_local_notifications: ^9.0.0
  charts_flutter: ^0.12.0
  confetti: ^0.6.0
  animated_text_kit: ^4.2.1
  fluttertoast: ^8.0.9
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/InstagramRound-Regular.ttf
  fonts:
    - family: InstagramRound
      fonts:
        - asset: assets/fonts/InstagramRound-Regular.ttf
          weight: 400
